USE QLBANHANGPIZZA
GO
IF OBJECT_ID('sp_EditEMP', 'P') IS NOT NULL
	DROP PROC sp_EditEMP
GO

CREATE PROC sp_EditEMP 
	@ID_PRO CHAR(11),
	@NAMEPRO nvarchar(50),
	@ID_CATE char(11),
	@QUANTITY char (11),
	@UNIT nvarchar(5),
	@PICTURE varchar(50),
	@UNITPRICEPRO char(11),
	@STATUS_PRO nvarchar(100)
AS
BEGIN
	UPDATE [dbo].[PRODUCTS] SET [NAMEPRO] = @NAMEPRO, [ID_CATE] = @ID_CATE,[QUANTITY]= @QUANTITY,
	[UNIT]= @UNIT, [PICTURE]= @PICTURE, [UNITPRICEPRO]= @UNITPRICEPRO, [STATUS_PRO]=@STATUS_PRO
	WHERE ID_PRO = @ID_PRO
END
GO

--TẠO PROC LẤY GIÁ TRỊ CUỐI CÙNG CỦA BẢNG PRODUCT
IF OBJECT_ID('sp_getLastProduct', 'P') IS NOT NULL
	DROP PROC sp_getLastProduct
GO

CREATE PROC sp_getLastProduct
AS
	SELECT TOP 1 * FROM dbo.PRODUCTS ORDER BY ID_PRO DESC
GO

--KIỂM TRA PRODUCT ID CÓ GIỐNG TRONG BẢNG PRODUCT KHÔNG
IF OBJECT_ID('sp_CheckNamePro_Product', 'P') IS NOT NULL
	DROP PROC sp_CheckNamePro_Product
GO

CREATE PROC sp_CheckNamePro_Product 
	@namePro CHAR(11)	
AS
BEGIN
	IF EXISTS(SELECT * FROM dbo.PRODUCTS WHERE NAMEPRO LIKE '%@namePro%')
		SELECT 1
	ELSE
		SELECT 0
END
GO
--KIỂM TRA TÌM KIẾM
IF OBJECT_ID('sp_TimKiem', 'P') IS NOT NULL
	DROP PROC sp_TimKiem
GO

CREATE PROC sp_TimKiem 
	@chuoi nvarchar(50)	
AS
BEGIN
	SELECT * FROM dbo.PRODUCTS WHERE NAMEPRO LIKE '%@chuoi%'
		
END
GO
