//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHangPizza_GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public string ID_Emp { get; set; }
        public string ID_User { get; set; }
        public string PASS { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
