//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHangPizza_GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLDETAIL
    {
        public string ID_Bill { get; set; }
        public string ID_Pro { get; set; }
        public string Quantity { get; set; }
        public string UnitPrice { get; set; }
        public string IntoMoney { get; set; }
    
        public virtual BILL BILL { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
