//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHangPizza_GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.BILLDETAILs = new HashSet<BILLDETAIL>();
        }
    
        public string ID_PRO { get; set; }
        public string NAMEPRO { get; set; }
        public string ID_CATE { get; set; }
        public string QUANTITY { get; set; }
        public string UNIT { get; set; }
        public string PICTURE { get; set; }
        public string UNITPRICEPRO { get; set; }
        public string STATUS_PRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILLDETAIL> BILLDETAILs { get; set; }
        public virtual CATEGORy CATEGORy { get; set; }
    }
}
