//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHangPizza_GUI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLBANHANGPIZZAEntities : DbContext
    {
        public QLBANHANGPIZZAEntities()
            : base("name=QLBANHANGPIZZAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<BILL> BILLs { get; set; }
        public virtual DbSet<BILLDETAIL> BILLDETAILs { get; set; }
        public virtual DbSet<CATEGORy> CATEGORIES { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<EMPLOYEE_WORK> EMPLOYEE_WORK { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTS { get; set; }
    
        public virtual int SP_UPDATEEMPLOYEE(string iD_E, string name_E, string phone, string address, string positition)
        {
            var iD_EParameter = iD_E != null ?
                new ObjectParameter("ID_E", iD_E) :
                new ObjectParameter("ID_E", typeof(string));
    
            var name_EParameter = name_E != null ?
                new ObjectParameter("Name_E", name_E) :
                new ObjectParameter("Name_E", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var posititionParameter = positition != null ?
                new ObjectParameter("Positition", positition) :
                new ObjectParameter("Positition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATEEMPLOYEE", iD_EParameter, name_EParameter, phoneParameter, addressParameter, posititionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_getQuantityEmp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_getQuantityEmp");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_getQuantityEmp1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_getQuantityEmp1");
        }
    }
}
